// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsgnGT3ztuiuCN7gItlC7rtuFZm0bOcd8',
    appId: '1:23529323645:web:bbcc60917407351b9b8514',
    messagingSenderId: '23529323645',
    projectId: 'turquesa-hostal',
    authDomain: 'turquesa-hostal.firebaseapp.com',
    storageBucket: 'turquesa-hostal.firebasestorage.app',
    measurementId: 'G-RZ1JP2595J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWpQK4JnnIxqGc4EVWATvQgDGu2qLhJ5w',
    appId: '1:23529323645:android:5e6108e9b564845c9b8514',
    messagingSenderId: '23529323645',
    projectId: 'turquesa-hostal',
    storageBucket: 'turquesa-hostal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHDywz6O5tNGPuj7rmm4NfHlb6xngcBnI',
    appId: '1:23529323645:ios:68a93b1c1762b29a9b8514',
    messagingSenderId: '23529323645',
    projectId: 'turquesa-hostal',
    storageBucket: 'turquesa-hostal.firebasestorage.app',
    iosClientId: '23529323645-js9kc712p8bkaitv57d2pncjh2bckko9.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

}